### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by imzf** [muralivijay/android_kernel_msm8917#1]
I got a mistake
`drivers/input/touchscreen/focaltech/focaltech_flash.c:49:28: fatal error: include/firmware/FT8716_app_sample.i: No such file or directory
 #include FTS_UPGRADE_FW_APP
                            ^
compilation terminated.
scripts/Makefile.build:257: recipe for target 'drivers/input/touchscreen/focaltech/focaltech_flash.o' failed
make[4]: *** [drivers/input/touchscreen/focaltech/focaltech_flash.o] Error 1
scripts/Makefile.build:402: recipe for target 'drivers/input/touchscreen/focaltech' failed
make[3]: *** [drivers/input/touchscreen/focaltech] Error 2
scripts/Makefile.build:402: recipe for target 'drivers/input/touchscreen' failed
make[2]: *** [drivers/input/touchscreen] Error 2
scripts/Makefile.build:402: recipe for target 'drivers/input' failed
make[1]: *** [drivers/input] Error 2
Makefile:946: recipe for target 'drivers' failed
make: *** [drivers] Error 2`

**Comment by muralivijay** [comment]
clone this driver https://github.com/muralivijay/focaltech_touch

**Comment by imzf** [comment]
ok.thank you
